version: '3'

services:
  postgres:
    image: "postgres:9.6-alpine"
    container_name: postgres
    volumes:
      - scrum-data:/var/lib/postgresql/data
    ports:
      - 5432:5432 
    environment:
      - POSTGRES_DB=localhost
      - POSTGRES_USER=scrum
      - POSTGRES_PASSWORD=scrum
  backend-app:
    build: ./backend
    container_name: backend-app
    environment:
      - DB_SERVER=postgres
      - POSTGRES_DB=scrum
      - POSTGRES_USER=scrum
      - POSTGRES_PASSWORD=scrum
    ports:
      - 8080:8080
    links:
      - postgres
  frontend-app:
    build: ./frontend
    container_name: frontend-app
    ports:
      - 4200:80
    links:
      - backend-app