server:
  port: 8080

bootcamp:
  name: Projeto para o bootcamp DIO - Santander
  description: @project.description@
  version: @project.version@

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:db_bootcamp
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
